# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/game?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource



# mybatis-plus的配置
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.whut.springbootshiro.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pageheler的相关的配置
pagehelper:
  params: count=countSql
  support-methods-arguments: true
  reasonable: true
  helper-dialect: mysql









